// Public JS API for @babashka/fs, compiled from src/babashka/fs.cljc by squint.
// The squint-compiled names (exists_QMARK_, copy_tree, ...) are re-exported for
// direct interop; the friendly camelCase names are the documented JS surface.
// Generated by script/gen_index.cljs (bb gen-index).
import {
  absolute_QMARK_,
  absolutize,
  canonicalize,
  components,
  copy,
  copy_tree,
  create_dir,
  create_dirs,
  create_file,
  create_link,
  create_sym_link,
  create_temp_dir,
  create_temp_file,
  creation_time,
  cwd,
  delete$,
  delete_if_exists,
  delete_on_exit,
  delete_tree,
  directory_QMARK_,
  ends_with_QMARK_,
  exec_paths,
  executable_QMARK_,
  exists_QMARK_,
  expand_home,
  extension,
  file,
  file_name,
  file_separator,
  file_time__GT_instant,
  file_time__GT_millis,
  get_attribute,
  glob,
  glob__GT_regex,
  gunzip,
  gzip,
  hidden_QMARK_,
  home,
  instant__GT_file_time,
  last_modified_time,
  list_dir,
  list_dirs,
  match,
  millis__GT_file_time,
  modified_since,
  move,
  normalize,
  owner,
  parent,
  path,
  path_separator,
  posix__GT_str,
  posix_file_permissions,
  read_all_bytes,
  read_all_lines,
  read_attributes,
  read_attributes_STAR_,
  read_link,
  readable_QMARK_,
  real_path,
  regular_file_QMARK_,
  relative_QMARK_,
  relativize,
  root,
  same_file_QMARK_,
  set_attribute,
  set_creation_time,
  set_last_modified_time,
  set_posix_file_permissions,
  size,
  split_ext,
  split_paths,
  starts_with_QMARK_,
  str__GT_posix,
  strip_ext,
  sym_link_QMARK_,
  temp_dir,
  touch,
  unixify,
  unzip,
  update_file,
  walk_file_tree,
  which,
  which_all,
  windows_QMARK_,
  writable_QMARK_,
  write_bytes,
  write_lines,
  xdg_cache_home,
  xdg_config_home,
  xdg_data_home,
  xdg_state_home,
  zip,
} from './lib/babashka/fs.mjs';

// camelCase (or dashed) option keys are translated to the dashed keyword
// strings the squint-compiled functions read, e.g. {posixFilePermissions}
// and {visitFile} become {'posix-file-permissions'} / {'visit-file'}.
const kebabKey = (k) => k.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());
const isPlainObject = (x) =>
  x != null && typeof x === 'object' && Object.getPrototypeOf(x) === Object.prototype;
const kebabizeArg = (x) => {
  if (!isPlainObject(x)) return x;
  const out = {};
  for (const k of Object.keys(x)) out[kebabKey(k)] = x[k];
  return out;
};
const jsFriendly = (fn) => (...args) => fn(...args.map(kebabizeArg));

const isAbsolute = jsFriendly(absolute_QMARK_);
const copyTree = jsFriendly(copy_tree);
const createDir = jsFriendly(create_dir);
const createDirs = jsFriendly(create_dirs);
const createFile = jsFriendly(create_file);
const createLink = jsFriendly(create_link);
const createSymLink = jsFriendly(create_sym_link);
const createTempDir = jsFriendly(create_temp_dir);
const createTempFile = jsFriendly(create_temp_file);
const creationTime = jsFriendly(creation_time);
const deleteIfExists = jsFriendly(delete_if_exists);
const deleteOnExit = jsFriendly(delete_on_exit);
const deleteTree = jsFriendly(delete_tree);
const isDirectory = jsFriendly(directory_QMARK_);
const endsWith = jsFriendly(ends_with_QMARK_);
const execPaths = jsFriendly(exec_paths);
const isExecutable = jsFriendly(executable_QMARK_);
const exists = jsFriendly(exists_QMARK_);
const expandHome = jsFriendly(expand_home);
const fileName = jsFriendly(file_name);
const fileSeparator = file_separator;
const fileTimeToInstant = jsFriendly(file_time__GT_instant);
const fileTimeToMillis = jsFriendly(file_time__GT_millis);
const getAttribute = jsFriendly(get_attribute);
const globToRegex = jsFriendly(glob__GT_regex);
const isHidden = jsFriendly(hidden_QMARK_);
const instantToFileTime = jsFriendly(instant__GT_file_time);
const lastModifiedTime = jsFriendly(last_modified_time);
const listDir = jsFriendly(list_dir);
const listDirs = jsFriendly(list_dirs);
const millisToFileTime = jsFriendly(millis__GT_file_time);
const modifiedSince = jsFriendly(modified_since);
const pathSeparator = path_separator;
const posixToStr = jsFriendly(posix__GT_str);
const posixFilePermissions = jsFriendly(posix_file_permissions);
const readAllBytes = jsFriendly(read_all_bytes);
const readAllLines = jsFriendly(read_all_lines);
const readAttributes = jsFriendly(read_attributes);
const readAttributesRaw = jsFriendly(read_attributes_STAR_);
const readLink = jsFriendly(read_link);
const isReadable = jsFriendly(readable_QMARK_);
const realPath = jsFriendly(real_path);
const isRegularFile = jsFriendly(regular_file_QMARK_);
const isRelative = jsFriendly(relative_QMARK_);
const isSameFile = jsFriendly(same_file_QMARK_);
const setAttribute = jsFriendly(set_attribute);
const setCreationTime = jsFriendly(set_creation_time);
const setLastModifiedTime = jsFriendly(set_last_modified_time);
const setPosixFilePermissions = jsFriendly(set_posix_file_permissions);
const splitExt = jsFriendly(split_ext);
const splitPaths = jsFriendly(split_paths);
const startsWith = jsFriendly(starts_with_QMARK_);
const strToPosix = jsFriendly(str__GT_posix);
const stripExt = jsFriendly(strip_ext);
const isSymlink = jsFriendly(sym_link_QMARK_);
const tempDir = jsFriendly(temp_dir);
const updateFile = jsFriendly(update_file);
const walkFileTree = jsFriendly(walk_file_tree);
const whichAll = jsFriendly(which_all);
const isWindows = jsFriendly(windows_QMARK_);
const isWritable = jsFriendly(writable_QMARK_);
const writeBytes = jsFriendly(write_bytes);
const writeLines = jsFriendly(write_lines);
const xdgCacheHome = jsFriendly(xdg_cache_home);
const xdgConfigHome = jsFriendly(xdg_config_home);
const xdgDataHome = jsFriendly(xdg_data_home);
const xdgStateHome = jsFriendly(xdg_state_home);

export {
  // squint names
  absolute_QMARK_,
  absolutize,
  canonicalize,
  components,
  copy,
  copy_tree,
  create_dir,
  create_dirs,
  create_file,
  create_link,
  create_sym_link,
  create_temp_dir,
  create_temp_file,
  creation_time,
  cwd,
  delete$,
  delete_if_exists,
  delete_on_exit,
  delete_tree,
  directory_QMARK_,
  ends_with_QMARK_,
  exec_paths,
  executable_QMARK_,
  exists_QMARK_,
  expand_home,
  extension,
  file,
  file_name,
  file_separator,
  file_time__GT_instant,
  file_time__GT_millis,
  get_attribute,
  glob,
  glob__GT_regex,
  gunzip,
  gzip,
  hidden_QMARK_,
  home,
  instant__GT_file_time,
  last_modified_time,
  list_dir,
  list_dirs,
  match,
  millis__GT_file_time,
  modified_since,
  move,
  normalize,
  owner,
  parent,
  path,
  path_separator,
  posix__GT_str,
  posix_file_permissions,
  read_all_bytes,
  read_all_lines,
  read_attributes,
  read_attributes_STAR_,
  read_link,
  readable_QMARK_,
  real_path,
  regular_file_QMARK_,
  relative_QMARK_,
  relativize,
  root,
  same_file_QMARK_,
  set_attribute,
  set_creation_time,
  set_last_modified_time,
  set_posix_file_permissions,
  size,
  split_ext,
  split_paths,
  starts_with_QMARK_,
  str__GT_posix,
  strip_ext,
  sym_link_QMARK_,
  temp_dir,
  touch,
  unixify,
  unzip,
  update_file,
  walk_file_tree,
  which,
  which_all,
  windows_QMARK_,
  writable_QMARK_,
  write_bytes,
  write_lines,
  xdg_cache_home,
  xdg_config_home,
  xdg_data_home,
  xdg_state_home,
  zip,
  // friendly camelCase aliases
  isAbsolute,
  copyTree,
  createDir,
  createDirs,
  createFile,
  createLink,
  createSymLink,
  createTempDir,
  createTempFile,
  creationTime,
  deleteIfExists,
  deleteOnExit,
  deleteTree,
  isDirectory,
  endsWith,
  execPaths,
  isExecutable,
  exists,
  expandHome,
  fileName,
  fileSeparator,
  fileTimeToInstant,
  fileTimeToMillis,
  getAttribute,
  globToRegex,
  isHidden,
  instantToFileTime,
  lastModifiedTime,
  listDir,
  listDirs,
  millisToFileTime,
  modifiedSince,
  pathSeparator,
  posixToStr,
  posixFilePermissions,
  readAllBytes,
  readAllLines,
  readAttributes,
  readAttributesRaw,
  readLink,
  isReadable,
  realPath,
  isRegularFile,
  isRelative,
  isSameFile,
  setAttribute,
  setCreationTime,
  setLastModifiedTime,
  setPosixFilePermissions,
  splitExt,
  splitPaths,
  startsWith,
  strToPosix,
  stripExt,
  isSymlink,
  tempDir,
  updateFile,
  walkFileTree,
  whichAll,
  isWindows,
  isWritable,
  writeBytes,
  writeLines,
  xdgCacheHome,
  xdgConfigHome,
  xdgDataHome,
  xdgStateHome,
  // reserved-word names (no option translation, none needed)
  delete$ as delete,
};

// with-temp-dir is a compile-time macro; this is the JS-callable equivalent.
// Creates a temp dir, runs `callback(dir)`, then deletes it (unless `opts.keep`).
export function withTempDir(callback, opts) {
  const o = kebabizeArg(opts);
  const dir = create_temp_dir(o);
  try {
    return callback(dir);
  } finally {
    if (!(o && o.keep)) {
      delete_tree(dir, { force: true });
    }
  }
}
